"""create initial medical ai tables

Revision ID: dd54648f2aa8
Revises: 
Create Date: 2026-06-17 12:25:32.177913

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dd54648f2aa8'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patients',
    sa.Column('patient_id', sa.String(length=100), nullable=False),
    sa.Column('dataset_subject_id', sa.String(length=100), nullable=True),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('patient_id')
    )
    op.create_table('patient_cases',
    sa.Column('case_id', sa.String(length=100), nullable=False),
    sa.Column('patient_id', sa.String(length=100), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('disease_domain', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.patient_id'], ),
    sa.PrimaryKeyConstraint('case_id')
    )
    op.create_table('feature_sets',
    sa.Column('feature_set_id', sa.String(length=100), nullable=False),
    sa.Column('case_id', sa.String(length=100), nullable=False),
    sa.Column('features', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['patient_cases.case_id'], ),
    sa.PrimaryKeyConstraint('feature_set_id')
    )
    op.create_table('scans',
    sa.Column('scan_id', sa.String(length=100), nullable=False),
    sa.Column('case_id', sa.String(length=100), nullable=False),
    sa.Column('modality', sa.String(length=50), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('file_format', sa.String(length=20), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['patient_cases.case_id'], ),
    sa.PrimaryKeyConstraint('scan_id')
    )
    op.create_table('predictions',
    sa.Column('prediction_id', sa.String(length=100), nullable=False),
    sa.Column('case_id', sa.String(length=100), nullable=False),
    sa.Column('feature_set_id', sa.String(length=100), nullable=False),
    sa.Column('predicted_label', sa.String(length=100), nullable=False),
    sa.Column('probability', sa.Float(), nullable=False),
    sa.Column('threshold', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['patient_cases.case_id'], ),
    sa.ForeignKeyConstraint(['feature_set_id'], ['feature_sets.feature_set_id'], ),
    sa.PrimaryKeyConstraint('prediction_id')
    )
    op.create_table('visual_embeddings',
    sa.Column('embedding_id', sa.String(length=100), nullable=False),
    sa.Column('scan_id', sa.String(length=100), nullable=False),
    sa.Column('embedding_path', sa.String(length=500), nullable=False),
    sa.Column('embedding_dim', sa.Integer(), nullable=False),
    sa.Column('encoder', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.scan_id'], ),
    sa.PrimaryKeyConstraint('embedding_id')
    )
    op.create_table('anfis_rule_sets',
    sa.Column('anfis_rule_set_id', sa.String(length=100), nullable=False),
    sa.Column('prediction_id', sa.String(length=100), nullable=False),
    sa.Column('conditions', sa.Text(), nullable=False),
    sa.Column('strength', sa.Float(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['prediction_id'], ['predictions.prediction_id'], ),
    sa.PrimaryKeyConstraint('anfis_rule_set_id')
    )
    op.create_table('fusion_results',
    sa.Column('fusion_result_id', sa.String(length=100), nullable=False),
    sa.Column('prediction_id', sa.String(length=100), nullable=False),
    sa.Column('w_clinical', sa.Float(), nullable=False),
    sa.Column('w_visual', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['prediction_id'], ['predictions.prediction_id'], ),
    sa.PrimaryKeyConstraint('fusion_result_id')
    )
    op.create_table('prediction_scans',
    sa.Column('prediction_scan_id', sa.String(length=100), nullable=False),
    sa.Column('prediction_id', sa.String(length=100), nullable=False),
    sa.Column('scan_id', sa.String(length=100), nullable=False),
    sa.Column('modality', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['prediction_id'], ['predictions.prediction_id']),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.scan_id']),
    sa.PrimaryKeyConstraint('prediction_scan_id'),
    sa.UniqueConstraint('prediction_id', 'scan_id', name='uq_prediction_scan')
)
    op.create_table('visual_findings',
    sa.Column('finding_id', sa.String(length=100), nullable=False),
    sa.Column('scan_id', sa.String(length=100), nullable=False),
    sa.Column('prediction_id', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('source_model', sa.String(length=100), nullable=True),
    sa.Column('confidence', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['prediction_id'], ['predictions.prediction_id'], ),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.scan_id'], ),
    sa.PrimaryKeyConstraint('finding_id')
    )
    op.create_table('evidence_chunks',
    sa.Column('chunk_id', sa.String(length=100), nullable=False),
    sa.Column('chroma_doc_id', sa.String(length=200), nullable=False),
    sa.Column('prediction_id', sa.String(length=100), nullable=False),
    sa.Column('anfis_rule_set_id', sa.String(length=100), nullable=True),
    sa.Column('visual_finding_id', sa.String(length=100), nullable=True),
    sa.Column('evidence_type', sa.String(length=50), nullable=False),
    sa.Column('source_table', sa.String(length=100), nullable=False),
    sa.Column('source_id', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['anfis_rule_set_id'], ['anfis_rule_sets.anfis_rule_set_id'], ),
    sa.ForeignKeyConstraint(['prediction_id'], ['predictions.prediction_id'], ),
    sa.ForeignKeyConstraint(['visual_finding_id'], ['visual_findings.finding_id'], ),
    sa.PrimaryKeyConstraint('chunk_id'),
    sa.UniqueConstraint('chroma_doc_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('evidence_chunks')
    op.drop_table('visual_findings')
    op.drop_table('prediction_scans')
    op.drop_table('fusion_results')
    op.drop_table('anfis_rule_sets')
    op.drop_table('visual_embeddings')
    op.drop_table('predictions')
    op.drop_table('scans')
    op.drop_table('feature_sets')
    op.drop_table('patient_cases')
    op.drop_table('patients')
    # ### end Alembic commands ###
